USE [master]
GO

/****** Object:  Database [Daylight]    Script Date: 11/18/2013 6:28:17 AM ******/
CREATE DATABASE [Daylight]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Daylight', FILENAME = N'C:\Users\Windows\Daylight.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Daylight_log', FILENAME = N'C:\Users\Windows\Daylight_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Daylight] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Daylight].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Daylight] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Daylight] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Daylight] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Daylight] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Daylight] SET ARITHABORT OFF 
GO

ALTER DATABASE [Daylight] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Daylight] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Daylight] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Daylight] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Daylight] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Daylight] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Daylight] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Daylight] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Daylight] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Daylight] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Daylight] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Daylight] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Daylight] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Daylight] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Daylight] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Daylight] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Daylight] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Daylight] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Daylight] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Daylight] SET  MULTI_USER 
GO

ALTER DATABASE [Daylight] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Daylight] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Daylight] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Daylight] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Daylight] SET  READ_WRITE 
GO

