USE [Daylight]
GO

/****** Object:  Table [dbo].[RecordComponent]    Script Date: 11/19/2013 7:43:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RecordComponent](
	[ComponentCode] [varchar](6) NOT NULL,
	[Description] [varchar](max) NOT NULL,
 CONSTRAINT [PK_RecordComponent] PRIMARY KEY CLUSTERED 
(
	[ComponentCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

