//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Event : IStateEntity
    {
        public System.Guid EventId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Colour { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public bool AllDay { get; set; }
        public string Icon { get; set; }
    }
}
