//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalAidMember : IStateEntity
    {
        public System.Guid MemberId { get; set; }
        public System.Guid MedicalAidId { get; set; }
        public string MembershipNumber { get; set; }
        public string RelationshipToPatient { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string IdNumber { get; set; }
        public string Employer { get; set; }
    
        public virtual MedicalAid MedicalAid { get; set; }
    }
}
