//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalAid : IStateEntity
    {
        public MedicalAid()
        {
            this.MedicalAidMembers = new HashSet<MedicalAidMember>();
        }
    
        public System.Guid MedicalAidId { get; set; }
        public string MedicalAidName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<MedicalAidMember> MedicalAidMembers { get; set; }
    }
}
