//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class Patient : IStateEntity
    {
        public Patient()
        {
            this.Addresses = new HashSet<Address>();
            this.Names = new HashSet<Name>();
            this.Relationships = new HashSet<Relationship>();
            this.Telecoms = new HashSet<Telecom>();
            this.Conditions = new HashSet<Condition>();
            this.Medications = new HashSet<Medication>();
            this.Procedures = new HashSet<Procedure>();
            this.DeathReports = new HashSet<DeathReport>();
        }
    
        public System.Guid PatientId { get; set; }
        public bool IsDeleted { get; set; }
        public string Gender { get; set; }
        public string RelationshipStatus { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public bool DateOfBirthEstimate { get; set; }
        public System.DateTime DateBecamePatient { get; set; }
        public string Extention { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Name> Names { get; set; }
        public virtual ICollection<Relationship> Relationships { get; set; }
        public virtual ICollection<Telecom> Telecoms { get; set; }
        public virtual ICollection<Condition> Conditions { get; set; }
        public virtual ICollection<Medication> Medications { get; set; }
        public virtual ICollection<Procedure> Procedures { get; set; }
        public virtual ICollection<DeathReport> DeathReports { get; set; }
    }
}
