//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBill : IStateEntity
    {
        public System.Guid BillId { get; set; }
        public System.Guid ConditionId { get; set; }
        public System.Guid PatientId { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Condition Condition { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
