//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment : IStateEntity
    {
        public Payment()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public System.Guid PaymentTransactionId { get; set; }
        public System.Guid PaymentMethodId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
