//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod : IStateEntity
    {
        public PaymentMethod()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public System.Guid PaymentMethodId { get; set; }
        public string Details { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
