//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public System.Guid Id { get; set; }
        public System.Guid PatientId { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public bool Dependent { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Type { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
