//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daylight.WebApi.Contracts.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vital : IStateEntity
    {
        public System.Guid ObservationId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime DateRecorded { get; set; }
        public Nullable<double> Pulse { get; set; }
        public Nullable<double> BloodGlucose { get; set; }
        public Nullable<short> DiastolicBP { get; set; }
        public Nullable<short> SystolicBP { get; set; }
        public Nullable<double> BodyTemperature { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
    }
}
