using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Daylight.WebApi.Mvc.Models.Security
{
    /// <summary>
    /// Describes a View Model for a Login
    /// </summary>
    public class LoginViewModel
    {
        /// <summary>
        /// Gets or sets the unique name of the user.
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Gets or sets the password for the user.
        /// </summary>
        public string Password { get; set; }

        /// <summary>
        /// Gets or sets the message generated by the Login process.
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the credentials specified by this model are valid.
        /// </summary>
        /// <value>
        ///   <c>true</c> if valid; otherwise, <c>false</c>.
        /// </value>
        public bool Valid { get; set; }
    }
}